name: frysish
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0                  #https://pub.dev/packages/auto_size_text
  
  dynamic_color: ^1.6.8                   #https://pub.dev/packages/dynamic_color

  get_it: ^7.6.7
  graphql: ^5.1.3
  
  build_runner: ^2.4.7                    #https://pub.dev/packages/build_runner
  
  flutter:
    sdk: flutter                          #https://flutter.dev/docs/development/tools/sdk/releases?tab=macos
  flutter_launcher_icons: ^0.13.1         #https://pub.dev/packages/flutter_launcher_icons
  flutter_localization: ^0.2.0            #https://pub.dev/packages/flutter_localization
  flutter_offline: ^3.0.1                 #https://pub.dev/packages/flutter_offline
  flutter_onboarding_slider: ^1.0.11      #https://pub.dev/packages/flutter_onboarding_slider
  flutter_svg: ^2.0.9                     #https://pub.dev/packages/flutter_svg
  
  google_fonts: ^6.1.0                    #https://pub.dev/packages/google_fonts

  path_provider: ^2.1.1                   #https://pub.dev/packages/path_provider
  shared_preferences: ^2.2.2              #https://pub.dev/packages/shared_preferences
  intl: ^0.18.1                           #https://pub.dev/packages/intl               

  logger: ^2.0.2+1                        #https://pub.dev/packages/logger          
  mockito: ^5.4.4                         #https://pub.dev/packages/mockito                  
  
  url_launcher: ^6.2.2                    #https://pub.dev/packages/url_launcher            
  provider: ^6.1.1                        #https://pub.dev/packages/provider                
  cupertino_icons: ^1.0.6                 #https://pub.dev/packages/cupertino_icons
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter                          #https://flutter.dev/docs/testing       
  flutter_lints: ^3.0.1                   #https://pub.dev/packages/flutter_lints            

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/flags/
    - assets/logos/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"