name: frysish
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:

  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter                          #https://flutter.dev/docs/development/tools/sdk/releases?tab=macos
  flutter_localization: ^0.2.2
  flutter_offline: ^4.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  graphql: ^5.1.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  select_dialog: ^2.0.2
  shared_preferences: ^2.3.2
  # system_theme: ^3.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter                          #https://flutter.dev/docs/testing       
  flutter_lints: 4.0.0                   #https://pub.dev/packages/flutter_lints            

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/flags/
    - assets/logos/
    - assets/gifs/

flutter_launcher_icons:
  image_path: "assets/logos/logo.png"
  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: true