import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class Dyntranslate {
  static String translate(BuildContext context, String dynKey) {
    var localizations = AppLocalizations.of(context);
    switch (dynKey) {
      case "choose":
        return localizations!.choose;
      case "abbrYes":
        return localizations!.abbrYes;
      case "account":
        return localizations!.account;
      case "addFavorites":
        return localizations!.addFavorites;
      case "alltext":
        return localizations!.alltext;
      case "animalName":
        return localizations!.animalName;
      case "article":
        return localizations!.article;
      case "based":
        return localizations!.based;
      case "birdName":
        return localizations!.birdName;
      case "borrowing":
        return localizations!.borrowing;
      case "caseAcc":
        return localizations!.caseAcc;
      case "caseNom":
        return localizations!.caseNom;
      case "casePar":
        return localizations!.casePar;
      case "checkfields":
        return localizations!.checkfields;
      case "collocation":
        return localizations!.collocation;
      case "collocations":
        return localizations!.collocations;
      case "completedict":
        return localizations!.completedict;
      case "constructionAttr":
        return localizations!.constructionAttr;
      case "copy":
        return localizations!.copy;
      case "countryName":
        return localizations!.countryName;
      case "darkTheme":
        return localizations!.darkTheme;
      case "definition":
        return localizations!.definition;
      case "degreeCmp":
        return localizations!.degreeCmp;
      case "degreeSup":
        return localizations!.degreeSup;
      case "diminutiveDim":
        return localizations!.diminutiveDim;
      case "duchtisms":
        return localizations!.duchtisms;
      case "en":
        return localizations!.en;
      case "enterText":
        return localizations!.enterText;
      case "example":
        return localizations!.example;
      case "examples":
        return localizations!.examples;
      case "favorites":
        return localizations!.favorites;
      case "feedback":
        return localizations!.feedback;
      case "firstpage":
        return localizations!.firstpage;
      case "forms":
        return localizations!.forms;
      case "found":
        return localizations!.found;
      case "fry":
        return localizations!.fry;
      case "fryXbiltsk":
        return localizations!.fryXbiltsk;
      case "genderCom":
        return localizations!.genderCom;
      case "genderFem":
        return localizations!.genderFem;
      case "genderMasc":
        return localizations!.genderMasc;
      case "genderNeut":
        return localizations!.genderNeut;
      case "geoName":
        return localizations!.geoName;
      case "grammar":
        return localizations!.grammar;
      case "history":
        return localizations!.history;
      case "hom":
        return localizations!.hom;
      case "homs":
        return localizations!.homs;
      case "inflectionInfl":
        return localizations!.inflectionInfl;
      case "inflectionUninf":
        return localizations!.inflectionUninf;
      case "information":
        return localizations!.information;
      case "inside":
        return localizations!.inside;
      case "issues":
        return localizations!.issues;
      case "lastpage":
        return localizations!.lastpage;
      case "lemmas":
        return localizations!.lemmas;
      case "lightTheme":
        return localizations!.lightTheme;
      case "locale":
        return localizations!.locale;
      case "more":
        return localizations!.more;
      case "muchMore":
        return localizations!.muchMore;
      case "nextpage":
        return localizations!.nextpage;
      case "nl":
        return localizations!.nl;
      case "notranslations":
        return localizations!.notranslations;
      case "noresults":
        return localizations!.noresults;
      case "noSpaces":
        return localizations!.noSpaces;
      case "numberColl":
        return localizations!.numberColl;
      case "numberPlur":
        return localizations!.numberPlur;
      case "numberPtan":
        return localizations!.numberPtan;
      case "numberSing":
        return localizations!.numberSing;
      case "numtypeCard":
        return localizations!.numtypeCard;
      case "numtypeOrd":
        return localizations!.numtypeOrd;
      case "options":
        return localizations!.options;
      case "orgName":
        return localizations!.orgName;
      case "orthresults":
        return localizations!.orthresults;
      case "paradigm":
        return localizations!.paradigm;
      case "person1":
        return localizations!.person1;
      case "person2":
        return localizations!.person2;
      case "person3":
        return localizations!.person3;
      case "personName":
        return localizations!.personName;
      case "placeName":
        return localizations!.placeName;
      case "plantName":
        return localizations!.plantName;
      case "politeForm":
        return localizations!.politeForm;
      case "pos":
        return localizations!.pos;
      case "poschoice":
        return localizations!.poschoice;
      case "possYes":
        return localizations!.possYes;
      case "predicatePred":
        return localizations!.predicatePred;
      case "prefixYes":
        return localizations!.prefixYes;
      case "prevpage":
        return localizations!.prevpage;
      case "primaryColor":
        return localizations!.primaryColor;
      case "pron":
        return localizations!.pron;
      case "pronounClitic":
        return localizations!.pronounClitic;
      case "prontypeArt":
        return localizations!.prontypeArt;
      case "prontypeDem":
        return localizations!.prontypeDem;
      case "prontypeInd":
        return localizations!.prontypeInd;
      case "prontypePrs":
        return localizations!.prontypePrs;
      case "prontypeRel":
        return localizations!.prontypeRel;
      case "proverb":
        return localizations!.proverb;
      case "proverbs":
        return localizations!.proverbs;
      case "referrers":
        return localizations!.referrers;
      case "reflexYes":
        return localizations!.reflexYes;
      case "result":
        return localizations!.result;
      case "retrHistory":
        return localizations!.retrHistory;
      case "search":
        return localizations!.search;
      case "searchedText":
        return localizations!.searchedText;
      case "searchhelp":
        return localizations!.searchhelp;
      case "searchlang":
        return localizations!.searchlang;
      case "searchterm":
        return localizations!.searchterm;
      case "searchtext":
        return localizations!.searchtext;
      case "section":
        return localizations!.section;
      case "see":
        return localizations!.see;
      case "sense":
        return localizations!.sense;
      case "senses":
        return localizations!.senses;
      case "settings":
        return localizations!.settings;
      case "showfrom":
        return localizations!.showfrom;
      case "slogan":
        return localizations!.slogan;
      case "stage":
        return localizations!.stage;
      case "stress":
        return localizations!.stress;
      case "structure":
        return localizations!.structure;
      case "suffixYes":
        return localizations!.suffixYes;
      case "swapLang":
        return localizations!.swapLang;
      case "synonym":
        return localizations!.synonym;
      case "synonyms":
        return localizations!.synonyms;
      case "systemTheme":
        return localizations!.systemTheme;
      case "tenseFut":
        return localizations!.tenseFut;
      case "tensePast":
        return localizations!.tensePast;
      case "tensePres":
        return localizations!.tensePres;
      case "textoffset":
        return localizations!.textoffset;
      case "textresults":
        return localizations!.textresults;
      case "textSearch":
        return localizations!.textSearch;
      case "theme":
        return localizations!.theme;
      case "translate":
        return localizations!.translate;
      case "translation":
        return localizations!.translation;
      case "usgConcerning":
        return localizations!.usgConcerning;
      case "usgConnotation":
        return localizations!.usgConnotation;
      case "usgFreq":
        return localizations!.usgFreq;
      case "usgHint":
        return localizations!.usgHint;
      case "usgLang":
        return localizations!.usgLang;
      case "usgMedium":
        return localizations!.usgMedium;
      case "usgStyle":
        return localizations!.usgStyle;
      case "usgTime":
        return localizations!.usgTime;
      case "variant":
        return localizations!.variant;
      case "variants":
        return localizations!.variants;
      case "verbformGer":
        return localizations!.verbformGer;
      case "verbformInf":
        return localizations!.verbformInf;
      case "verbformPart":
        return localizations!.verbformPart;
      case "vertalingen":
        return localizations!.vertalingen;
      case "viewExamples":
        return localizations!.viewExamples;
      case "textsearch":
        return localizations!.textsearch;
      case "welcome":
        return localizations!.welcome;
      case "wordform":
        return localizations!.wordform;
      case "wordforms":
        return localizations!.wordforms;
      case "appFunctions":
        return localizations!.appFunctions;
      case "present":
        return localizations!.present;
      case "past":
        return localizations!.past;
      case "presentParticiple":
        return localizations!.presentParticiple;
      case "pastParticiple":
        return localizations!.pastParticiple;
      case "person1Sing":
        return localizations!.person1Sing;
      case "person2Sing":
        return localizations!.person2Sing;
      case "person2PlurFormal":
        return localizations!.person2PlurFormal;
      case "person3Sing":
        return localizations!.person3Sing;
      case "person1Plur":
        return localizations!.person1Plur;
      case "person2Plur":
        return localizations!.person2Plur;
      case "person3Plur":
        return localizations!.person3Plur;
      case "wildcards":
        return localizations!.wildcards;
      case "doubleqoutes":
        return localizations!.doubleqoutes;
      case "occurrence":
        return localizations!.occurrence;
      case "andOr":
        return localizations!.andOr;
      case "launch":
        return localizations!.launch;
      case "pres_1_sing":
        return localizations!.pres_1_sing;
      case "pres_2_sing":
        return localizations!.pres_2_sing;
      case "pres_drop":
        return localizations!.pres_drop;
      case "pres_clitic":
        return localizations!.pres_clitic;
      case "pres_3_sing":
        return localizations!.pres_3_sing;
      case "pres_polite":
        return localizations!.pres_polite;
      case "past_1_sing":
        return localizations!.past_1_sing;
      case "past_2_sing":
        return localizations!.past_2_sing;
      case "past_drop":
        return localizations!.past_drop;
      case "past_clitic":
        return localizations!.past_clitic;
      case "past_3_sing":
        return localizations!.past_3_sing;
      case "past_polite":
        return localizations!.past_polite;
      case "pres_1_plur":
        return localizations!.pres_1_plur;
      case "pres_2_plur":
        return localizations!.pres_2_plur;
      case "pres_3_plur":
        return localizations!.pres_3_plur;
      case "past_1_plur":
        return localizations!.past_1_plur;
      case "past_2_plur":
        return localizations!.past_2_plur;
      case "past_3_plur":
        return localizations!.past_3_plur;
      case "pres_part":
        return localizations!.pres_part;
      case "pres_part_infl":
        return localizations!.pres_part_infl;
      case "past_part":
        return localizations!.past_part;
      case "verb_noun":
        return localizations!.verb_noun;
      case "inf":
        return localizations!.inf;
      case "sing":
        return localizations!.sing;
      case "plur":
        return localizations!.plur;
      case "plur_tantum":
        return localizations!.plur_tantum;
      case "sing_tantum":
        return localizations!.sing_tantum;
      case "dim_sing":
        return localizations!.dim_sing;
      case "dim_plur":
        return localizations!.dim_plur;
      case "pos_uninfl":
        return localizations!.pos_uninfl;
      case "pos_infl":
        return localizations!.pos_infl;
      case "cmp_uninfl":
        return localizations!.cmp_uninfl;
      case "cmp_infl":
        return localizations!.cmp_infl;
      case "sup_uninfl":
        return localizations!.sup_uninfl;
      case "sup_infl":
        return localizations!.sup_infl;
      case "par_pos":
        return localizations!.par_pos;
      case "par_cmp":
        return localizations!.par_cmp;
      case "par_pos_plur":
        return localizations!.par_pos_plur;
      case "par_cmp_plur":
        return localizations!.par_cmp_plur;
      case "par_sup_plur":
        return localizations!.par_sup_plur;
      case "unsupported":
        return localizations!.unsupported;
      case "base":
        return localizations!.base;
    }
    return dynKey;
  }
}
