// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:frysish/__generated__/schema.schema.gql.dart'
    show
        GCategoryType,
        GGramType,
        GLangType,
        GMessageLevel,
        GNameType,
        GUsgType;
import 'package:frysish/src/graphql/__generated__/autocomplete.data.gql.dart'
    show
        GautocompleteData,
        GautocompleteData_lemmasearch,
        GautocompleteData_lemmasearch_lemmas;
import 'package:frysish/src/graphql/__generated__/autocomplete.req.gql.dart'
    show GautocompleteReq;
import 'package:frysish/src/graphql/__generated__/autocomplete.var.gql.dart'
    show GautocompleteVars;
import 'package:frysish/src/graphql/__generated__/details_article.data.gql.dart'
    show
        GdetailsArticleData,
        GdetailsArticleData_details,
        GdetailsArticleData_details_lemma;
import 'package:frysish/src/graphql/__generated__/details_article.req.gql.dart'
    show GdetailsArticleReq;
import 'package:frysish/src/graphql/__generated__/details_article.var.gql.dart'
    show GdetailsArticleVars;
import 'package:frysish/src/graphql/__generated__/details_examples.data.gql.dart'
    show
        GdetailsExamplesData_details_texts,
        GdetailsExamplesData_details_texts__asExample_text_text,
        GdetailsExamplesData_details_texts__asExample_text_text__asI_textI,
        GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asQ_textQ,
        GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ,
        GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asI_textI,
        GdetailsExamplesData_details_texts__asExample_translations_text_text,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asQ_textQ,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asI_textI,
        GdetailsExamplesData,
        GdetailsExamplesData_details,
        GdetailsExamplesData_details_texts__asExample,
        GdetailsExamplesData_details_texts__asExample_text,
        GdetailsExamplesData_details_texts__asExample_text_text__asI,
        GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asQ,
        GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asQ_textQ__asT,
        GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asQ_textQ__base,
        GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asT,
        GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__base,
        GdetailsExamplesData_details_texts__asExample_text_text__asL,
        GdetailsExamplesData_details_texts__asExample_text_text__asL_link,
        GdetailsExamplesData_details_texts__asExample_text_text__asQ,
        GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asI,
        GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asI_textI__asT,
        GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asI_textI__base,
        GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asT,
        GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__base,
        GdetailsExamplesData_details_texts__asExample_text_text__asT,
        GdetailsExamplesData_details_texts__asExample_text_text__base,
        GdetailsExamplesData_details_texts__asExample_translations,
        GdetailsExamplesData_details_texts__asExample_translations_text,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asI,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asQ,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asQ_textQ__asT,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asQ_textQ__base,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asT,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__base,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asL,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asL_link,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asI,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asI_textI__asT,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asI_textI__base,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asT,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__base,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__asT,
        GdetailsExamplesData_details_texts__asExample_translations_text_text__base,
        GdetailsExamplesData_details_texts__base;
import 'package:frysish/src/graphql/__generated__/details_examples.req.gql.dart'
    show GdetailsExamplesReq;
import 'package:frysish/src/graphql/__generated__/details_examples.var.gql.dart'
    show GdetailsExamplesVars;
import 'package:frysish/src/graphql/__generated__/details_grammar.data.gql.dart'
    show
        GdetailsGrammarData,
        GdetailsGrammarData_details,
        GdetailsGrammarData_details_lemma;
import 'package:frysish/src/graphql/__generated__/details_grammar.req.gql.dart'
    show GdetailsGrammarReq;
import 'package:frysish/src/graphql/__generated__/details_grammar.var.gql.dart'
    show GdetailsGrammarVars;
import 'package:frysish/src/graphql/__generated__/details_lemma.data.gql.dart'
    show
        GdetailsLemmaData_details_lemma_note_text_text,
        GdetailsLemmaData_details_lemma_note_text_text__asI_textI,
        GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asQ_textQ,
        GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ,
        GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asI_textI,
        GdetailsLemmaData,
        GdetailsLemmaData_details,
        GdetailsLemmaData_details_lemma,
        GdetailsLemmaData_details_lemma_note,
        GdetailsLemmaData_details_lemma_note_text,
        GdetailsLemmaData_details_lemma_note_text_text__asI,
        GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asQ,
        GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asQ_textQ__asT,
        GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asQ_textQ__base,
        GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asT,
        GdetailsLemmaData_details_lemma_note_text_text__asI_textI__base,
        GdetailsLemmaData_details_lemma_note_text_text__asL,
        GdetailsLemmaData_details_lemma_note_text_text__asL_link,
        GdetailsLemmaData_details_lemma_note_text_text__asQ,
        GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asI,
        GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asI_textI__asT,
        GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asI_textI__base,
        GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asT,
        GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__base,
        GdetailsLemmaData_details_lemma_note_text_text__asT,
        GdetailsLemmaData_details_lemma_note_text_text__base,
        GdetailsLemmaData_details_lemma_subForms,
        GdetailsLemmaData_details_lemma_usage;
import 'package:frysish/src/graphql/__generated__/details_lemma.req.gql.dart'
    show GdetailsLemmaReq;
import 'package:frysish/src/graphql/__generated__/details_lemma.var.gql.dart'
    show GdetailsLemmaVars;
import 'package:frysish/src/graphql/__generated__/details_pronunciation.data.gql.dart'
    show
        GdetailsPronunciationData,
        GdetailsPronunciationData_details,
        GdetailsPronunciationData_details_lemma;
import 'package:frysish/src/graphql/__generated__/details_pronunciation.req.gql.dart'
    show GdetailsPronunciationReq;
import 'package:frysish/src/graphql/__generated__/details_pronunciation.var.gql.dart'
    show GdetailsPronunciationVars;
import 'package:frysish/src/graphql/__generated__/details_proverbs.data.gql.dart'
    show
        GdetailsProverbsData_details_texts,
        GdetailsProverbsData_details_texts__asProverb_text_text,
        GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI,
        GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asQ_textQ,
        GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ,
        GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asI_textI,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asQ_textQ,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asI_textI,
        GdetailsProverbsData,
        GdetailsProverbsData_details,
        GdetailsProverbsData_details_texts__asProverb,
        GdetailsProverbsData_details_texts__asProverb_text,
        GdetailsProverbsData_details_texts__asProverb_text_text__asI,
        GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asQ,
        GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asQ_textQ__asT,
        GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asQ_textQ__base,
        GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asT,
        GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__base,
        GdetailsProverbsData_details_texts__asProverb_text_text__asL,
        GdetailsProverbsData_details_texts__asProverb_text_text__asL_link,
        GdetailsProverbsData_details_texts__asProverb_text_text__asQ,
        GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asI,
        GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asI_textI__asT,
        GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asI_textI__base,
        GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asT,
        GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__base,
        GdetailsProverbsData_details_texts__asProverb_text_text__asT,
        GdetailsProverbsData_details_texts__asProverb_text_text__base,
        GdetailsProverbsData_details_texts__asProverb_translations,
        GdetailsProverbsData_details_texts__asProverb_translations_text,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asQ,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__asT,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__base,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asT,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__base,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asL,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asL_link,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asI,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__asT,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__base,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asT,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__base,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__asT,
        GdetailsProverbsData_details_texts__asProverb_translations_text_text__base,
        GdetailsProverbsData_details_texts__base;
import 'package:frysish/src/graphql/__generated__/details_proverbs.req.gql.dart'
    show GdetailsProverbsReq;
import 'package:frysish/src/graphql/__generated__/details_proverbs.var.gql.dart'
    show GdetailsProverbsVars;
import 'package:frysish/src/graphql/__generated__/details_subforms.data.gql.dart'
    show
        GdetailsSubFormsData_details_lemma_subForms,
        GdetailsSubFormsData,
        GdetailsSubFormsData_details,
        GdetailsSubFormsData_details_lemma,
        GdetailsSubFormsData_details_lemma_subForms__asDutchism,
        GdetailsSubFormsData_details_lemma_subForms__asParadigm,
        GdetailsSubFormsData_details_lemma_subForms__asParadigmCategory,
        GdetailsSubFormsData_details_lemma_subForms__asParadigmCategory_forms,
        GdetailsSubFormsData_details_lemma_subForms__asSynonym,
        GdetailsSubFormsData_details_lemma_subForms__asVariant,
        GdetailsSubFormsData_details_lemma_subForms__base;
import 'package:frysish/src/graphql/__generated__/details_subforms.req.gql.dart'
    show GdetailsSubFormsReq;
import 'package:frysish/src/graphql/__generated__/details_subforms.var.gql.dart'
    show GdetailsSubFormsVars;
import 'package:frysish/src/graphql/__generated__/details_translations.data.gql.dart'
    show
        GdetailsTranslationsData_details_translations_note_text_text,
        GdetailsTranslationsData_details_translations_note_text_text__asI_textI,
        GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asQ_textQ,
        GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ,
        GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asI_textI,
        GdetailsTranslationsData,
        GdetailsTranslationsData_details,
        GdetailsTranslationsData_details_translations,
        GdetailsTranslationsData_details_translations_note,
        GdetailsTranslationsData_details_translations_note_text,
        GdetailsTranslationsData_details_translations_note_text_text__asI,
        GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asQ,
        GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asQ_textQ__asT,
        GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asQ_textQ__base,
        GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asT,
        GdetailsTranslationsData_details_translations_note_text_text__asI_textI__base,
        GdetailsTranslationsData_details_translations_note_text_text__asL,
        GdetailsTranslationsData_details_translations_note_text_text__asL_link,
        GdetailsTranslationsData_details_translations_note_text_text__asQ,
        GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asI,
        GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asI_textI__asT,
        GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asI_textI__base,
        GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asT,
        GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__base,
        GdetailsTranslationsData_details_translations_note_text_text__asT,
        GdetailsTranslationsData_details_translations_note_text_text__base,
        GdetailsTranslationsData_details_translations_subForms,
        GdetailsTranslationsData_details_translations_usage;
import 'package:frysish/src/graphql/__generated__/details_translations.req.gql.dart'
    show GdetailsTranslationsReq;
import 'package:frysish/src/graphql/__generated__/details_translations.var.gql.dart'
    show GdetailsTranslationsVars;
import 'package:frysish/src/graphql/__generated__/search_lemma.data.gql.dart'
    show
        GsearchLemmaData,
        GsearchLemmaData_lemmasearch,
        GsearchLemmaData_lemmasearch_lemmas,
        GsearchLemmaData_lemmasearch_lemmas_link,
        GsearchLemmaData_lemmasearch_lemmas_subForms,
        GsearchLemmaData_lemmasearch_lemmas_translations;
import 'package:frysish/src/graphql/__generated__/search_lemma.req.gql.dart'
    show GsearchLemmaReq;
import 'package:frysish/src/graphql/__generated__/search_lemma.var.gql.dart'
    show GsearchLemmaVars;
import 'package:frysish/src/graphql/__generated__/search_lemma_subforms.data.gql.dart'
    show
        GSearchLemmaSubFormData_lemmasearch_lemmas_subForms,
        GSearchLemmaSubFormData,
        GSearchLemmaSubFormData_lemmasearch,
        GSearchLemmaSubFormData_lemmasearch_lemmas,
        GSearchLemmaSubFormData_lemmasearch_lemmas_link,
        GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asDutchism,
        GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asParadigm,
        GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asParadigmCategory,
        GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asParadigmCategory_forms,
        GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asSynonym,
        GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asVariant,
        GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__base,
        GSearchLemmaSubFormData_lemmasearch_lemmas_translations,
        GSearchLemmaSubFormData_lemmasearch_message;
import 'package:frysish/src/graphql/__generated__/search_lemma_subforms.req.gql.dart'
    show GSearchLemmaSubFormReq;
import 'package:frysish/src/graphql/__generated__/search_lemma_subforms.var.gql.dart'
    show GSearchLemmaSubFormVars;
import 'package:frysish/src/graphql/__generated__/text_examples.data.gql.dart'
    show
        GtextExamplesData_textsearch_texts,
        GtextExamplesData_textsearch_texts__asExample_text_text,
        GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI,
        GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ,
        GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ,
        GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI,
        GtextExamplesData,
        GtextExamplesData_textsearch,
        GtextExamplesData_textsearch_texts__asExample,
        GtextExamplesData_textsearch_texts__asExample_text,
        GtextExamplesData_textsearch_texts__asExample_text_text__asI,
        GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asQ,
        GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ__asT,
        GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ__base,
        GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asT,
        GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__base,
        GtextExamplesData_textsearch_texts__asExample_text_text__asL,
        GtextExamplesData_textsearch_texts__asExample_text_text__asL_link,
        GtextExamplesData_textsearch_texts__asExample_text_text__asQ,
        GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asI,
        GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI__asT,
        GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI__base,
        GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asT,
        GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__base,
        GtextExamplesData_textsearch_texts__asExample_text_text__asT,
        GtextExamplesData_textsearch_texts__asExample_text_text__base,
        GtextExamplesData_textsearch_texts__asExample_translations,
        GtextExamplesData_textsearch_texts__asExample_translations_text,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ__asT,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ__base,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asT,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__base,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asL,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asL_link,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI__asT,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI__base,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asT,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__base,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__asT,
        GtextExamplesData_textsearch_texts__asExample_translations_text_text__base,
        GtextExamplesData_textsearch_texts__base;
import 'package:frysish/src/graphql/__generated__/text_examples.req.gql.dart'
    show GtextExamplesReq;
import 'package:frysish/src/graphql/__generated__/text_examples.var.gql.dart'
    show GtextExamplesVars;
import 'package:frysish/src/graphql/__generated__/text_proverbs.data.gql.dart'
    show
        GtextProverbsData_textsearch_texts,
        GtextProverbsData_textsearch_texts__asProverb_text_text,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI,
        GtextProverbsData,
        GtextProverbsData_textsearch,
        GtextProverbsData_textsearch_texts__asProverb,
        GtextProverbsData_textsearch_texts__asProverb_text,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asI,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asQ,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ__asT,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ__base,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asT,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__base,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asL,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asL_link,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asQ,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI__asT,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI__base,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asT,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__base,
        GtextProverbsData_textsearch_texts__asProverb_text_text__asT,
        GtextProverbsData_textsearch_texts__asProverb_text_text__base,
        GtextProverbsData_textsearch_texts__asProverb_translations,
        GtextProverbsData_textsearch_texts__asProverb_translations_text,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__asT,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__base,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asT,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__base,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asL,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asL_link,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__asT,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__base,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asT,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__base,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asT,
        GtextProverbsData_textsearch_texts__asProverb_translations_text_text__base,
        GtextProverbsData_textsearch_texts__base;
import 'package:frysish/src/graphql/__generated__/text_proverbs.req.gql.dart'
    show GtextProverbsReq;
import 'package:frysish/src/graphql/__generated__/text_proverbs.var.gql.dart'
    show GtextProverbsVars;
import 'package:frysish/src/graphql/fragments/__generated__/lemma_details.data.gql.dart'
    show
        GLemmaDetailsData_note_text_text,
        GLemmaDetailsData_note_text_text__asI_textI,
        GLemmaDetailsData_note_text_text__asI_textI__asQ_textQ,
        GLemmaDetailsData_note_text_text__asQ_textQ,
        GLemmaDetailsData_note_text_text__asQ_textQ__asI_textI,
        GLemmaDetailsData,
        GLemmaDetailsData_note,
        GLemmaDetailsData_note_text,
        GLemmaDetailsData_note_text_text__asI,
        GLemmaDetailsData_note_text_text__asI_textI__asQ,
        GLemmaDetailsData_note_text_text__asI_textI__asQ_textQ__asT,
        GLemmaDetailsData_note_text_text__asI_textI__asQ_textQ__base,
        GLemmaDetailsData_note_text_text__asI_textI__asT,
        GLemmaDetailsData_note_text_text__asI_textI__base,
        GLemmaDetailsData_note_text_text__asL,
        GLemmaDetailsData_note_text_text__asL_link,
        GLemmaDetailsData_note_text_text__asQ,
        GLemmaDetailsData_note_text_text__asQ_textQ__asI,
        GLemmaDetailsData_note_text_text__asQ_textQ__asI_textI__asT,
        GLemmaDetailsData_note_text_text__asQ_textQ__asI_textI__base,
        GLemmaDetailsData_note_text_text__asQ_textQ__asT,
        GLemmaDetailsData_note_text_text__asQ_textQ__base,
        GLemmaDetailsData_note_text_text__asT,
        GLemmaDetailsData_note_text_text__base,
        GLemmaDetailsData_subForms,
        GLemmaDetailsData_usage;
import 'package:frysish/src/graphql/fragments/__generated__/lemma_details.req.gql.dart'
    show GLemmaDetailsReq;
import 'package:frysish/src/graphql/fragments/__generated__/lemma_details.var.gql.dart'
    show GLemmaDetailsVars;
import 'package:frysish/src/graphql/fragments/__generated__/link_details.data.gql.dart'
    show GLinkDetailsData;
import 'package:frysish/src/graphql/fragments/__generated__/link_details.req.gql.dart'
    show GLinkDetailsReq;
import 'package:frysish/src/graphql/fragments/__generated__/link_details.var.gql.dart'
    show GLinkDetailsVars;
import 'package:frysish/src/graphql/fragments/__generated__/paradigm_processing.data.gql.dart'
    show
        GParadigmProcessingData_note_text_text,
        GParadigmProcessingData_note_text_text__asI_textI,
        GParadigmProcessingData_note_text_text__asI_textI__asQ_textQ,
        GParadigmProcessingData_note_text_text__asQ_textQ,
        GParadigmProcessingData_note_text_text__asQ_textQ__asI_textI,
        GParadigmProcessingData,
        GParadigmProcessingData_note,
        GParadigmProcessingData_note_text,
        GParadigmProcessingData_note_text_text__asI,
        GParadigmProcessingData_note_text_text__asI_textI__asQ,
        GParadigmProcessingData_note_text_text__asI_textI__asQ_textQ__asT,
        GParadigmProcessingData_note_text_text__asI_textI__asQ_textQ__base,
        GParadigmProcessingData_note_text_text__asI_textI__asT,
        GParadigmProcessingData_note_text_text__asI_textI__base,
        GParadigmProcessingData_note_text_text__asL,
        GParadigmProcessingData_note_text_text__asL_link,
        GParadigmProcessingData_note_text_text__asQ,
        GParadigmProcessingData_note_text_text__asQ_textQ__asI,
        GParadigmProcessingData_note_text_text__asQ_textQ__asI_textI__asT,
        GParadigmProcessingData_note_text_text__asQ_textQ__asI_textI__base,
        GParadigmProcessingData_note_text_text__asQ_textQ__asT,
        GParadigmProcessingData_note_text_text__asQ_textQ__base,
        GParadigmProcessingData_note_text_text__asT,
        GParadigmProcessingData_note_text_text__base;
import 'package:frysish/src/graphql/fragments/__generated__/paradigm_processing.req.gql.dart'
    show GParadigmProcessingReq;
import 'package:frysish/src/graphql/fragments/__generated__/paradigm_processing.var.gql.dart'
    show GParadigmProcessingVars;
import 'package:frysish/src/graphql/fragments/__generated__/subForm_processing.data.gql.dart'
    show
        GSubFormProcessingData,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asQ_textQ,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asI_textI,
        GSubFormProcessingData__asParadigm_note_text_text,
        GSubFormProcessingData__asParadigm_note_text_text__asI_textI,
        GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asQ_textQ,
        GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ,
        GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asI_textI,
        GSubFormProcessingData__asDutchism,
        GSubFormProcessingData__asParadigm,
        GSubFormProcessingData__asParadigmCategory,
        GSubFormProcessingData__asParadigmCategory_forms,
        GSubFormProcessingData__asParadigmCategory_forms_note,
        GSubFormProcessingData__asParadigmCategory_forms_note_text,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asQ,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asQ_textQ__asT,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asQ_textQ__base,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asT,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__base,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asL,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asL_link,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asI,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asI_textI__asT,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asI_textI__base,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asT,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__base,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asT,
        GSubFormProcessingData__asParadigmCategory_forms_note_text_text__base,
        GSubFormProcessingData__asParadigm_note,
        GSubFormProcessingData__asParadigm_note_text,
        GSubFormProcessingData__asParadigm_note_text_text__asI,
        GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asQ,
        GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asQ_textQ__asT,
        GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asQ_textQ__base,
        GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asT,
        GSubFormProcessingData__asParadigm_note_text_text__asI_textI__base,
        GSubFormProcessingData__asParadigm_note_text_text__asL,
        GSubFormProcessingData__asParadigm_note_text_text__asL_link,
        GSubFormProcessingData__asParadigm_note_text_text__asQ,
        GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asI,
        GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asI_textI__asT,
        GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asI_textI__base,
        GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asT,
        GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__base,
        GSubFormProcessingData__asParadigm_note_text_text__asT,
        GSubFormProcessingData__asParadigm_note_text_text__base,
        GSubFormProcessingData__asSynonym,
        GSubFormProcessingData__asVariant,
        GSubFormProcessingData__base;
import 'package:frysish/src/graphql/fragments/__generated__/subForm_processing.req.gql.dart'
    show GSubFormProcessingReq;
import 'package:frysish/src/graphql/fragments/__generated__/subForm_processing.var.gql.dart'
    show GSubFormProcessingVars;
import 'package:frysish/src/graphql/fragments/__generated__/text_processing.data.gql.dart'
    show
        GTextProcessingData_text,
        GTextProcessingData_text__asI_textI,
        GTextProcessingData_text__asI_textI__asQ_textQ,
        GTextProcessingData_text__asQ_textQ,
        GTextProcessingData_text__asQ_textQ__asI_textI,
        GTextProcessingData,
        GTextProcessingData_text__asI,
        GTextProcessingData_text__asI_textI__asQ,
        GTextProcessingData_text__asI_textI__asQ_textQ__asT,
        GTextProcessingData_text__asI_textI__asQ_textQ__base,
        GTextProcessingData_text__asI_textI__asT,
        GTextProcessingData_text__asI_textI__base,
        GTextProcessingData_text__asL,
        GTextProcessingData_text__asL_link,
        GTextProcessingData_text__asQ,
        GTextProcessingData_text__asQ_textQ__asI,
        GTextProcessingData_text__asQ_textQ__asI_textI__asT,
        GTextProcessingData_text__asQ_textQ__asI_textI__base,
        GTextProcessingData_text__asQ_textQ__asT,
        GTextProcessingData_text__asQ_textQ__base,
        GTextProcessingData_text__asT,
        GTextProcessingData_text__base;
import 'package:frysish/src/graphql/fragments/__generated__/text_processing.req.gql.dart'
    show GTextProcessingReq;
import 'package:frysish/src/graphql/fragments/__generated__/text_processing.var.gql.dart'
    show GTextProcessingVars;
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..add(GLemmaDetailsData_note_text_text.serializer)
  ..add(GLemmaDetailsData_note_text_text__asI_textI.serializer)
  ..add(GLemmaDetailsData_note_text_text__asI_textI__asQ_textQ.serializer)
  ..add(GLemmaDetailsData_note_text_text__asQ_textQ.serializer)
  ..add(GLemmaDetailsData_note_text_text__asQ_textQ__asI_textI.serializer)
  ..add(GParadigmProcessingData_note_text_text.serializer)
  ..add(GParadigmProcessingData_note_text_text__asI_textI.serializer)
  ..add(GParadigmProcessingData_note_text_text__asI_textI__asQ_textQ.serializer)
  ..add(GParadigmProcessingData_note_text_text__asQ_textQ.serializer)
  ..add(GParadigmProcessingData_note_text_text__asQ_textQ__asI_textI.serializer)
  ..add(GSearchLemmaSubFormData_lemmasearch_lemmas_subForms.serializer)
  ..add(GSubFormProcessingData.serializer)
  ..add(GSubFormProcessingData__asParadigmCategory_forms_note_text_text
      .serializer)
  ..add(
      GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI
          .serializer)
  ..add(
      GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(
      GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ
          .serializer)
  ..add(
      GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GSubFormProcessingData__asParadigm_note_text_text.serializer)
  ..add(GSubFormProcessingData__asParadigm_note_text_text__asI_textI.serializer)
  ..add(GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asQ_textQ
      .serializer)
  ..add(GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ.serializer)
  ..add(GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asI_textI
      .serializer)
  ..add(GTextProcessingData_text.serializer)
  ..add(GTextProcessingData_text__asI_textI.serializer)
  ..add(GTextProcessingData_text__asI_textI__asQ_textQ.serializer)
  ..add(GTextProcessingData_text__asQ_textQ.serializer)
  ..add(GTextProcessingData_text__asQ_textQ__asI_textI.serializer)
  ..add(GdetailsExamplesData_details_texts.serializer)
  ..add(GdetailsExamplesData_details_texts__asExample_text_text.serializer)
  ..add(GdetailsExamplesData_details_texts__asExample_text_text__asI_textI
      .serializer)
  ..add(
      GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ
      .serializer)
  ..add(
      GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GdetailsExamplesData_details_texts__asExample_translations_text_text
      .serializer)
  ..add(
      GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI
          .serializer)
  ..add(
      GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(
      GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ
          .serializer)
  ..add(
      GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GdetailsLemmaData_details_lemma_note_text_text.serializer)
  ..add(GdetailsLemmaData_details_lemma_note_text_text__asI_textI.serializer)
  ..add(GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asQ_textQ
      .serializer)
  ..add(GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ.serializer)
  ..add(GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asI_textI
      .serializer)
  ..add(GdetailsProverbsData_details_texts.serializer)
  ..add(GdetailsProverbsData_details_texts__asProverb_text_text.serializer)
  ..add(GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI
      .serializer)
  ..add(
      GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ
      .serializer)
  ..add(
      GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GdetailsProverbsData_details_texts__asProverb_translations_text_text
      .serializer)
  ..add(
      GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI
          .serializer)
  ..add(
      GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(
      GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ
          .serializer)
  ..add(
      GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GdetailsSubFormsData_details_lemma_subForms.serializer)
  ..add(GdetailsTranslationsData_details_translations_note_text_text.serializer)
  ..add(GdetailsTranslationsData_details_translations_note_text_text__asI_textI
      .serializer)
  ..add(
      GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ
      .serializer)
  ..add(
      GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtextExamplesData_textsearch_texts.serializer)
  ..add(GtextExamplesData_textsearch_texts__asExample_text_text.serializer)
  ..add(GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI
      .serializer)
  ..add(
      GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ
      .serializer)
  ..add(
      GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtextExamplesData_textsearch_texts__asExample_translations_text_text
      .serializer)
  ..add(
      GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI
          .serializer)
  ..add(
      GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(
      GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ
          .serializer)
  ..add(
      GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtextProverbsData_textsearch_texts.serializer)
  ..add(GtextProverbsData_textsearch_texts__asProverb_text_text.serializer)
  ..add(GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI
      .serializer)
  ..add(
      GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ
      .serializer)
  ..add(
      GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtextProverbsData_textsearch_texts__asProverb_translations_text_text
      .serializer)
  ..add(
      GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI
          .serializer)
  ..add(
      GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(
      GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ
          .serializer)
  ..add(
      GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI
          .serializer)
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GCategoryType,
  GGramType,
  GLangType,
  GLemmaDetailsData,
  GLemmaDetailsData_note,
  GLemmaDetailsData_note_text,
  GLemmaDetailsData_note_text_text__asI,
  GLemmaDetailsData_note_text_text__asI_textI__asQ,
  GLemmaDetailsData_note_text_text__asI_textI__asQ_textQ__asT,
  GLemmaDetailsData_note_text_text__asI_textI__asQ_textQ__base,
  GLemmaDetailsData_note_text_text__asI_textI__asT,
  GLemmaDetailsData_note_text_text__asI_textI__base,
  GLemmaDetailsData_note_text_text__asL,
  GLemmaDetailsData_note_text_text__asL_link,
  GLemmaDetailsData_note_text_text__asQ,
  GLemmaDetailsData_note_text_text__asQ_textQ__asI,
  GLemmaDetailsData_note_text_text__asQ_textQ__asI_textI__asT,
  GLemmaDetailsData_note_text_text__asQ_textQ__asI_textI__base,
  GLemmaDetailsData_note_text_text__asQ_textQ__asT,
  GLemmaDetailsData_note_text_text__asQ_textQ__base,
  GLemmaDetailsData_note_text_text__asT,
  GLemmaDetailsData_note_text_text__base,
  GLemmaDetailsData_subForms,
  GLemmaDetailsData_usage,
  GLemmaDetailsReq,
  GLemmaDetailsVars,
  GLinkDetailsData,
  GLinkDetailsReq,
  GLinkDetailsVars,
  GMessageLevel,
  GNameType,
  GParadigmProcessingData,
  GParadigmProcessingData_note,
  GParadigmProcessingData_note_text,
  GParadigmProcessingData_note_text_text__asI,
  GParadigmProcessingData_note_text_text__asI_textI__asQ,
  GParadigmProcessingData_note_text_text__asI_textI__asQ_textQ__asT,
  GParadigmProcessingData_note_text_text__asI_textI__asQ_textQ__base,
  GParadigmProcessingData_note_text_text__asI_textI__asT,
  GParadigmProcessingData_note_text_text__asI_textI__base,
  GParadigmProcessingData_note_text_text__asL,
  GParadigmProcessingData_note_text_text__asL_link,
  GParadigmProcessingData_note_text_text__asQ,
  GParadigmProcessingData_note_text_text__asQ_textQ__asI,
  GParadigmProcessingData_note_text_text__asQ_textQ__asI_textI__asT,
  GParadigmProcessingData_note_text_text__asQ_textQ__asI_textI__base,
  GParadigmProcessingData_note_text_text__asQ_textQ__asT,
  GParadigmProcessingData_note_text_text__asQ_textQ__base,
  GParadigmProcessingData_note_text_text__asT,
  GParadigmProcessingData_note_text_text__base,
  GParadigmProcessingReq,
  GParadigmProcessingVars,
  GSearchLemmaSubFormData,
  GSearchLemmaSubFormData_lemmasearch,
  GSearchLemmaSubFormData_lemmasearch_lemmas,
  GSearchLemmaSubFormData_lemmasearch_lemmas_link,
  GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asDutchism,
  GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asParadigm,
  GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asParadigmCategory,
  GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asParadigmCategory_forms,
  GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asSynonym,
  GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__asVariant,
  GSearchLemmaSubFormData_lemmasearch_lemmas_subForms__base,
  GSearchLemmaSubFormData_lemmasearch_lemmas_translations,
  GSearchLemmaSubFormData_lemmasearch_message,
  GSearchLemmaSubFormReq,
  GSearchLemmaSubFormVars,
  GSubFormProcessingData__asDutchism,
  GSubFormProcessingData__asParadigm,
  GSubFormProcessingData__asParadigmCategory,
  GSubFormProcessingData__asParadigmCategory_forms,
  GSubFormProcessingData__asParadigmCategory_forms_note,
  GSubFormProcessingData__asParadigmCategory_forms_note_text,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asQ,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asQ_textQ__asT,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asQ_textQ__base,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__asT,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asI_textI__base,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asL,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asL_link,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asI,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asI_textI__asT,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asI_textI__base,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__asT,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asQ_textQ__base,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__asT,
  GSubFormProcessingData__asParadigmCategory_forms_note_text_text__base,
  GSubFormProcessingData__asParadigm_note,
  GSubFormProcessingData__asParadigm_note_text,
  GSubFormProcessingData__asParadigm_note_text_text__asI,
  GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asQ,
  GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asQ_textQ__asT,
  GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asQ_textQ__base,
  GSubFormProcessingData__asParadigm_note_text_text__asI_textI__asT,
  GSubFormProcessingData__asParadigm_note_text_text__asI_textI__base,
  GSubFormProcessingData__asParadigm_note_text_text__asL,
  GSubFormProcessingData__asParadigm_note_text_text__asL_link,
  GSubFormProcessingData__asParadigm_note_text_text__asQ,
  GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asI,
  GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asI_textI__asT,
  GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asI_textI__base,
  GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__asT,
  GSubFormProcessingData__asParadigm_note_text_text__asQ_textQ__base,
  GSubFormProcessingData__asParadigm_note_text_text__asT,
  GSubFormProcessingData__asParadigm_note_text_text__base,
  GSubFormProcessingData__asSynonym,
  GSubFormProcessingData__asVariant,
  GSubFormProcessingData__base,
  GSubFormProcessingReq,
  GSubFormProcessingVars,
  GTextProcessingData,
  GTextProcessingData_text__asI,
  GTextProcessingData_text__asI_textI__asQ,
  GTextProcessingData_text__asI_textI__asQ_textQ__asT,
  GTextProcessingData_text__asI_textI__asQ_textQ__base,
  GTextProcessingData_text__asI_textI__asT,
  GTextProcessingData_text__asI_textI__base,
  GTextProcessingData_text__asL,
  GTextProcessingData_text__asL_link,
  GTextProcessingData_text__asQ,
  GTextProcessingData_text__asQ_textQ__asI,
  GTextProcessingData_text__asQ_textQ__asI_textI__asT,
  GTextProcessingData_text__asQ_textQ__asI_textI__base,
  GTextProcessingData_text__asQ_textQ__asT,
  GTextProcessingData_text__asQ_textQ__base,
  GTextProcessingData_text__asT,
  GTextProcessingData_text__base,
  GTextProcessingReq,
  GTextProcessingVars,
  GUsgType,
  GautocompleteData,
  GautocompleteData_lemmasearch,
  GautocompleteData_lemmasearch_lemmas,
  GautocompleteReq,
  GautocompleteVars,
  GdetailsArticleData,
  GdetailsArticleData_details,
  GdetailsArticleData_details_lemma,
  GdetailsArticleReq,
  GdetailsArticleVars,
  GdetailsExamplesData,
  GdetailsExamplesData_details,
  GdetailsExamplesData_details_texts__asExample,
  GdetailsExamplesData_details_texts__asExample_text,
  GdetailsExamplesData_details_texts__asExample_text_text__asI,
  GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asQ,
  GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asQ_textQ__asT,
  GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asQ_textQ__base,
  GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__asT,
  GdetailsExamplesData_details_texts__asExample_text_text__asI_textI__base,
  GdetailsExamplesData_details_texts__asExample_text_text__asL,
  GdetailsExamplesData_details_texts__asExample_text_text__asL_link,
  GdetailsExamplesData_details_texts__asExample_text_text__asQ,
  GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asI,
  GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asI_textI__asT,
  GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asI_textI__base,
  GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__asT,
  GdetailsExamplesData_details_texts__asExample_text_text__asQ_textQ__base,
  GdetailsExamplesData_details_texts__asExample_text_text__asT,
  GdetailsExamplesData_details_texts__asExample_text_text__base,
  GdetailsExamplesData_details_texts__asExample_translations,
  GdetailsExamplesData_details_texts__asExample_translations_text,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asI,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asQ,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asQ_textQ__asT,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asQ_textQ__base,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__asT,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asI_textI__base,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asL,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asL_link,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asI,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asI_textI__asT,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asI_textI__base,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__asT,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asQ_textQ__base,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__asT,
  GdetailsExamplesData_details_texts__asExample_translations_text_text__base,
  GdetailsExamplesData_details_texts__base,
  GdetailsExamplesReq,
  GdetailsExamplesVars,
  GdetailsGrammarData,
  GdetailsGrammarData_details,
  GdetailsGrammarData_details_lemma,
  GdetailsGrammarReq,
  GdetailsGrammarVars,
  GdetailsLemmaData,
  GdetailsLemmaData_details,
  GdetailsLemmaData_details_lemma,
  GdetailsLemmaData_details_lemma_note,
  GdetailsLemmaData_details_lemma_note_text,
  GdetailsLemmaData_details_lemma_note_text_text__asI,
  GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asQ,
  GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asQ_textQ__asT,
  GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asQ_textQ__base,
  GdetailsLemmaData_details_lemma_note_text_text__asI_textI__asT,
  GdetailsLemmaData_details_lemma_note_text_text__asI_textI__base,
  GdetailsLemmaData_details_lemma_note_text_text__asL,
  GdetailsLemmaData_details_lemma_note_text_text__asL_link,
  GdetailsLemmaData_details_lemma_note_text_text__asQ,
  GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asI,
  GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asI_textI__asT,
  GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asI_textI__base,
  GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__asT,
  GdetailsLemmaData_details_lemma_note_text_text__asQ_textQ__base,
  GdetailsLemmaData_details_lemma_note_text_text__asT,
  GdetailsLemmaData_details_lemma_note_text_text__base,
  GdetailsLemmaData_details_lemma_subForms,
  GdetailsLemmaData_details_lemma_usage,
  GdetailsLemmaReq,
  GdetailsLemmaVars,
  GdetailsPronunciationData,
  GdetailsPronunciationData_details,
  GdetailsPronunciationData_details_lemma,
  GdetailsPronunciationReq,
  GdetailsPronunciationVars,
  GdetailsProverbsData,
  GdetailsProverbsData_details,
  GdetailsProverbsData_details_texts__asProverb,
  GdetailsProverbsData_details_texts__asProverb_text,
  GdetailsProverbsData_details_texts__asProverb_text_text__asI,
  GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asQ,
  GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asQ_textQ__asT,
  GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asQ_textQ__base,
  GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__asT,
  GdetailsProverbsData_details_texts__asProverb_text_text__asI_textI__base,
  GdetailsProverbsData_details_texts__asProverb_text_text__asL,
  GdetailsProverbsData_details_texts__asProverb_text_text__asL_link,
  GdetailsProverbsData_details_texts__asProverb_text_text__asQ,
  GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asI,
  GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asI_textI__asT,
  GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asI_textI__base,
  GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__asT,
  GdetailsProverbsData_details_texts__asProverb_text_text__asQ_textQ__base,
  GdetailsProverbsData_details_texts__asProverb_text_text__asT,
  GdetailsProverbsData_details_texts__asProverb_text_text__base,
  GdetailsProverbsData_details_texts__asProverb_translations,
  GdetailsProverbsData_details_texts__asProverb_translations_text,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asQ,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__asT,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__base,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__asT,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asI_textI__base,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asL,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asL_link,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asI,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__asT,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__base,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__asT,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asQ_textQ__base,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__asT,
  GdetailsProverbsData_details_texts__asProverb_translations_text_text__base,
  GdetailsProverbsData_details_texts__base,
  GdetailsProverbsReq,
  GdetailsProverbsVars,
  GdetailsSubFormsData,
  GdetailsSubFormsData_details,
  GdetailsSubFormsData_details_lemma,
  GdetailsSubFormsData_details_lemma_subForms__asDutchism,
  GdetailsSubFormsData_details_lemma_subForms__asParadigm,
  GdetailsSubFormsData_details_lemma_subForms__asParadigmCategory,
  GdetailsSubFormsData_details_lemma_subForms__asParadigmCategory_forms,
  GdetailsSubFormsData_details_lemma_subForms__asSynonym,
  GdetailsSubFormsData_details_lemma_subForms__asVariant,
  GdetailsSubFormsData_details_lemma_subForms__base,
  GdetailsSubFormsReq,
  GdetailsSubFormsVars,
  GdetailsTranslationsData,
  GdetailsTranslationsData_details,
  GdetailsTranslationsData_details_translations,
  GdetailsTranslationsData_details_translations_note,
  GdetailsTranslationsData_details_translations_note_text,
  GdetailsTranslationsData_details_translations_note_text_text__asI,
  GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asQ,
  GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asQ_textQ__asT,
  GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asQ_textQ__base,
  GdetailsTranslationsData_details_translations_note_text_text__asI_textI__asT,
  GdetailsTranslationsData_details_translations_note_text_text__asI_textI__base,
  GdetailsTranslationsData_details_translations_note_text_text__asL,
  GdetailsTranslationsData_details_translations_note_text_text__asL_link,
  GdetailsTranslationsData_details_translations_note_text_text__asQ,
  GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asI,
  GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asI_textI__asT,
  GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asI_textI__base,
  GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__asT,
  GdetailsTranslationsData_details_translations_note_text_text__asQ_textQ__base,
  GdetailsTranslationsData_details_translations_note_text_text__asT,
  GdetailsTranslationsData_details_translations_note_text_text__base,
  GdetailsTranslationsData_details_translations_subForms,
  GdetailsTranslationsData_details_translations_usage,
  GdetailsTranslationsReq,
  GdetailsTranslationsVars,
  GsearchLemmaData,
  GsearchLemmaData_lemmasearch,
  GsearchLemmaData_lemmasearch_lemmas,
  GsearchLemmaData_lemmasearch_lemmas_link,
  GsearchLemmaData_lemmasearch_lemmas_subForms,
  GsearchLemmaData_lemmasearch_lemmas_translations,
  GsearchLemmaReq,
  GsearchLemmaVars,
  GtextExamplesData,
  GtextExamplesData_textsearch,
  GtextExamplesData_textsearch_texts__asExample,
  GtextExamplesData_textsearch_texts__asExample_text,
  GtextExamplesData_textsearch_texts__asExample_text_text__asI,
  GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asQ,
  GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ__asT,
  GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ__base,
  GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__asT,
  GtextExamplesData_textsearch_texts__asExample_text_text__asI_textI__base,
  GtextExamplesData_textsearch_texts__asExample_text_text__asL,
  GtextExamplesData_textsearch_texts__asExample_text_text__asL_link,
  GtextExamplesData_textsearch_texts__asExample_text_text__asQ,
  GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asI,
  GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI__asT,
  GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI__base,
  GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__asT,
  GtextExamplesData_textsearch_texts__asExample_text_text__asQ_textQ__base,
  GtextExamplesData_textsearch_texts__asExample_text_text__asT,
  GtextExamplesData_textsearch_texts__asExample_text_text__base,
  GtextExamplesData_textsearch_texts__asExample_translations,
  GtextExamplesData_textsearch_texts__asExample_translations_text,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ__asT,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ__base,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__asT,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asI_textI__base,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asL,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asL_link,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI__asT,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI__base,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asT,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asQ_textQ__base,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__asT,
  GtextExamplesData_textsearch_texts__asExample_translations_text_text__base,
  GtextExamplesData_textsearch_texts__base,
  GtextExamplesReq,
  GtextExamplesVars,
  GtextProverbsData,
  GtextProverbsData_textsearch,
  GtextProverbsData_textsearch_texts__asProverb,
  GtextProverbsData_textsearch_texts__asProverb_text,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asI,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asQ,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ__asT,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ__base,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__asT,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asI_textI__base,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asL,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asL_link,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asQ,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI__asT,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI__base,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__asT,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asQ_textQ__base,
  GtextProverbsData_textsearch_texts__asProverb_text_text__asT,
  GtextProverbsData_textsearch_texts__asProverb_text_text__base,
  GtextProverbsData_textsearch_texts__asProverb_translations,
  GtextProverbsData_textsearch_texts__asProverb_translations_text,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__asT,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__base,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asT,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asI_textI__base,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asL,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asL_link,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__asT,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__base,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asT,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__base,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__asT,
  GtextProverbsData_textsearch_texts__asProverb_translations_text_text__base,
  GtextProverbsData_textsearch_texts__base,
  GtextProverbsReq,
  GtextProverbsVars,
])
final Serializers serializers = _serializersBuilder.build();
