// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:frysish/__generated__/schema.schema.gql.dart'
    show
        GCategoryType,
        GGramType,
        GLangType,
        GMessageLevel,
        GNameType,
        GUsgType;
import 'package:frysish/src/graphql/__generated__/autocompleteQuery.data.gql.dart'
    show
        GautocompleteData,
        GautocompleteData_lemmasearch,
        GautocompleteData_lemmasearch_lemmas,
        GautocompleteData_lemmasearch_message;
import 'package:frysish/src/graphql/__generated__/autocompleteQuery.req.gql.dart'
    show GautocompleteReq;
import 'package:frysish/src/graphql/__generated__/autocompleteQuery.var.gql.dart'
    show GautocompleteVars;
import 'package:frysish/src/graphql/__generated__/detailQuery.data.gql.dart'
    show
        GdetailsData_details_lemma_subForms,
        GdetailsData_details_translations_subForms,
        GlemmagraphData_subForms,
        GnestedtextgraphData,
        GnestedtextgraphData__asExample_text_text,
        GnestedtextgraphData__asExample_text_text__asI_textI,
        GnestedtextgraphData__asExample_text_text__asI_textI__asQ_textQ,
        GnestedtextgraphData__asExample_text_text__asQ_textQ,
        GnestedtextgraphData__asExample_text_text__asQ_textQ__asI_textI,
        GnestedtextgraphData__asExample_translations_text_text,
        GnestedtextgraphData__asExample_translations_text_text__asI_textI,
        GnestedtextgraphData__asExample_translations_text_text__asI_textI__asQ_textQ,
        GnestedtextgraphData__asExample_translations_text_text__asQ_textQ,
        GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asI_textI,
        GtextData_text_text,
        GtextData_text_text__asI_textI,
        GtextData_text_text__asI_textI__asQ_textQ,
        GtextData_text_text__asQ_textQ,
        GtextData_text_text__asQ_textQ__asI_textI,
        GtextgraphData,
        GtextgraphData__asProverb_text_text,
        GtextgraphData__asProverb_text_text__asI_textI,
        GtextgraphData__asProverb_text_text__asI_textI__asQ_textQ,
        GtextgraphData__asProverb_text_text__asQ_textQ,
        GtextgraphData__asProverb_text_text__asQ_textQ__asI_textI,
        GtextgraphData__asProverb_translations_text_text,
        GtextgraphData__asProverb_translations_text_text__asI_textI,
        GtextgraphData__asProverb_translations_text_text__asI_textI__asQ_textQ,
        GtextgraphData__asProverb_translations_text_text__asQ_textQ,
        GtextgraphData__asProverb_translations_text_text__asQ_textQ__asI_textI,
        GtexttransData_text_text,
        GtexttransData_text_text__asI_textI,
        GtexttransData_text_text__asI_textI__asQ_textQ,
        GtexttransData_text_text__asQ_textQ,
        GtexttransData_text_text__asQ_textQ__asI_textI,
        GtxtDetailsData_text,
        GtxtDetailsData_text__asI_textI,
        GtxtDetailsData_text__asI_textI__asQ_textQ,
        GtxtDetailsData_text__asQ_textQ,
        GtxtDetailsData_text__asQ_textQ__asI_textI,
        GdetailsData,
        GdetailsData_details,
        GdetailsData_details_lemma,
        GdetailsData_details_lemma_subForms__asDutchism,
        GdetailsData_details_lemma_subForms__asParadigm,
        GdetailsData_details_lemma_subForms__asParadigmCategory,
        GdetailsData_details_lemma_subForms__asParadigmCategory_forms,
        GdetailsData_details_lemma_subForms__asSynonym,
        GdetailsData_details_lemma_subForms__asVariant,
        GdetailsData_details_lemma_subForms__base,
        GdetailsData_details_texts,
        GdetailsData_details_translations,
        GdetailsData_details_translations_subForms__asDutchism,
        GdetailsData_details_translations_subForms__asParadigm,
        GdetailsData_details_translations_subForms__asParadigmCategory,
        GdetailsData_details_translations_subForms__asParadigmCategory_forms,
        GdetailsData_details_translations_subForms__asSynonym,
        GdetailsData_details_translations_subForms__asVariant,
        GdetailsData_details_translations_subForms__base,
        GlemmagraphData,
        GlemmagraphData_subForms__asDutchism,
        GlemmagraphData_subForms__asParadigm,
        GlemmagraphData_subForms__asParadigmCategory,
        GlemmagraphData_subForms__asParadigmCategory_forms,
        GlemmagraphData_subForms__asSynonym,
        GlemmagraphData_subForms__asVariant,
        GlemmagraphData_subForms__base,
        GlemmalinkData,
        GnestedtextgraphData__asExample,
        GnestedtextgraphData__asExample_text,
        GnestedtextgraphData__asExample_text_text__asI,
        GnestedtextgraphData__asExample_text_text__asI_textI__asQ,
        GnestedtextgraphData__asExample_text_text__asI_textI__asQ_textQ__asT,
        GnestedtextgraphData__asExample_text_text__asI_textI__asQ_textQ__base,
        GnestedtextgraphData__asExample_text_text__asI_textI__asT,
        GnestedtextgraphData__asExample_text_text__asI_textI__base,
        GnestedtextgraphData__asExample_text_text__asL,
        GnestedtextgraphData__asExample_text_text__asL_link,
        GnestedtextgraphData__asExample_text_text__asQ,
        GnestedtextgraphData__asExample_text_text__asQ_textQ__asI,
        GnestedtextgraphData__asExample_text_text__asQ_textQ__asI_textI__asT,
        GnestedtextgraphData__asExample_text_text__asQ_textQ__asI_textI__base,
        GnestedtextgraphData__asExample_text_text__asQ_textQ__asT,
        GnestedtextgraphData__asExample_text_text__asQ_textQ__base,
        GnestedtextgraphData__asExample_text_text__asT,
        GnestedtextgraphData__asExample_text_text__base,
        GnestedtextgraphData__asExample_translations,
        GnestedtextgraphData__asExample_translations_text,
        GnestedtextgraphData__asExample_translations_text_text__asI,
        GnestedtextgraphData__asExample_translations_text_text__asI_textI__asQ,
        GnestedtextgraphData__asExample_translations_text_text__asI_textI__asQ_textQ__asT,
        GnestedtextgraphData__asExample_translations_text_text__asI_textI__asQ_textQ__base,
        GnestedtextgraphData__asExample_translations_text_text__asI_textI__asT,
        GnestedtextgraphData__asExample_translations_text_text__asI_textI__base,
        GnestedtextgraphData__asExample_translations_text_text__asL,
        GnestedtextgraphData__asExample_translations_text_text__asL_link,
        GnestedtextgraphData__asExample_translations_text_text__asQ,
        GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asI,
        GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asI_textI__asT,
        GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asI_textI__base,
        GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asT,
        GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__base,
        GnestedtextgraphData__asExample_translations_text_text__asT,
        GnestedtextgraphData__asExample_translations_text_text__base,
        GnestedtextgraphData__base,
        GparData,
        GtextData,
        GtextData_text,
        GtextData_text_text__asI,
        GtextData_text_text__asI_textI__asQ,
        GtextData_text_text__asI_textI__asQ_textQ__asT,
        GtextData_text_text__asI_textI__asQ_textQ__base,
        GtextData_text_text__asI_textI__asT,
        GtextData_text_text__asI_textI__base,
        GtextData_text_text__asL,
        GtextData_text_text__asL_link,
        GtextData_text_text__asQ,
        GtextData_text_text__asQ_textQ__asI,
        GtextData_text_text__asQ_textQ__asI_textI__asT,
        GtextData_text_text__asQ_textQ__asI_textI__base,
        GtextData_text_text__asQ_textQ__asT,
        GtextData_text_text__asQ_textQ__base,
        GtextData_text_text__asT,
        GtextData_text_text__base,
        GtextgraphData__asProverb,
        GtextgraphData__asProverb_text,
        GtextgraphData__asProverb_text_text__asI,
        GtextgraphData__asProverb_text_text__asI_textI__asQ,
        GtextgraphData__asProverb_text_text__asI_textI__asQ_textQ__asT,
        GtextgraphData__asProverb_text_text__asI_textI__asQ_textQ__base,
        GtextgraphData__asProverb_text_text__asI_textI__asT,
        GtextgraphData__asProverb_text_text__asI_textI__base,
        GtextgraphData__asProverb_text_text__asL,
        GtextgraphData__asProverb_text_text__asL_link,
        GtextgraphData__asProverb_text_text__asQ,
        GtextgraphData__asProverb_text_text__asQ_textQ__asI,
        GtextgraphData__asProverb_text_text__asQ_textQ__asI_textI__asT,
        GtextgraphData__asProverb_text_text__asQ_textQ__asI_textI__base,
        GtextgraphData__asProverb_text_text__asQ_textQ__asT,
        GtextgraphData__asProverb_text_text__asQ_textQ__base,
        GtextgraphData__asProverb_text_text__asT,
        GtextgraphData__asProverb_text_text__base,
        GtextgraphData__asProverb_translations,
        GtextgraphData__asProverb_translations_text,
        GtextgraphData__asProverb_translations_text_text__asI,
        GtextgraphData__asProverb_translations_text_text__asI_textI__asQ,
        GtextgraphData__asProverb_translations_text_text__asI_textI__asQ_textQ__asT,
        GtextgraphData__asProverb_translations_text_text__asI_textI__asQ_textQ__base,
        GtextgraphData__asProverb_translations_text_text__asI_textI__asT,
        GtextgraphData__asProverb_translations_text_text__asI_textI__base,
        GtextgraphData__asProverb_translations_text_text__asL,
        GtextgraphData__asProverb_translations_text_text__asL_link,
        GtextgraphData__asProverb_translations_text_text__asQ,
        GtextgraphData__asProverb_translations_text_text__asQ_textQ__asI,
        GtextgraphData__asProverb_translations_text_text__asQ_textQ__asI_textI__asT,
        GtextgraphData__asProverb_translations_text_text__asQ_textQ__asI_textI__base,
        GtextgraphData__asProverb_translations_text_text__asQ_textQ__asT,
        GtextgraphData__asProverb_translations_text_text__asQ_textQ__base,
        GtextgraphData__asProverb_translations_text_text__asT,
        GtextgraphData__asProverb_translations_text_text__base,
        GtextgraphData__base,
        GtexttransData,
        GtexttransData_text,
        GtexttransData_text_text__asI,
        GtexttransData_text_text__asI_textI__asQ,
        GtexttransData_text_text__asI_textI__asQ_textQ__asT,
        GtexttransData_text_text__asI_textI__asQ_textQ__base,
        GtexttransData_text_text__asI_textI__asT,
        GtexttransData_text_text__asI_textI__base,
        GtexttransData_text_text__asL,
        GtexttransData_text_text__asL_link,
        GtexttransData_text_text__asQ,
        GtexttransData_text_text__asQ_textQ__asI,
        GtexttransData_text_text__asQ_textQ__asI_textI__asT,
        GtexttransData_text_text__asQ_textQ__asI_textI__base,
        GtexttransData_text_text__asQ_textQ__asT,
        GtexttransData_text_text__asQ_textQ__base,
        GtexttransData_text_text__asT,
        GtexttransData_text_text__base,
        GtxtDetailsData,
        GtxtDetailsData_text__asI,
        GtxtDetailsData_text__asI_textI__asQ,
        GtxtDetailsData_text__asI_textI__asQ_textQ__asT,
        GtxtDetailsData_text__asI_textI__asQ_textQ__base,
        GtxtDetailsData_text__asI_textI__asT,
        GtxtDetailsData_text__asI_textI__base,
        GtxtDetailsData_text__asL,
        GtxtDetailsData_text__asL_link,
        GtxtDetailsData_text__asQ,
        GtxtDetailsData_text__asQ_textQ__asI,
        GtxtDetailsData_text__asQ_textQ__asI_textI__asT,
        GtxtDetailsData_text__asQ_textQ__asI_textI__base,
        GtxtDetailsData_text__asQ_textQ__asT,
        GtxtDetailsData_text__asQ_textQ__base,
        GtxtDetailsData_text__asT,
        GtxtDetailsData_text__base;
import 'package:frysish/src/graphql/__generated__/detailQuery.req.gql.dart'
    show
        GdetailsReq,
        GlemmagraphReq,
        GlemmalinkReq,
        GnestedtextgraphReq,
        GparReq,
        GtextReq,
        GtextgraphReq,
        GtexttransReq,
        GtxtDetailsReq;
import 'package:frysish/src/graphql/__generated__/detailQuery.var.gql.dart'
    show
        GdetailsVars,
        GlemmagraphVars,
        GlemmalinkVars,
        GnestedtextgraphVars,
        GparVars,
        GtextVars,
        GtextgraphVars,
        GtexttransVars,
        GtxtDetailsVars;
import 'package:frysish/src/graphql/__generated__/fkwDetailQuery.data.gql.dart'
    show
        GfkwdetailsData_details_lemma_subForms,
        GfkwdetailsData,
        GfkwdetailsData_details,
        GfkwdetailsData_details_lemma,
        GfkwdetailsData_details_lemma_subForms__asParadigm,
        GfkwdetailsData_details_lemma_subForms__asParadigmCategory,
        GfkwdetailsData_details_lemma_subForms__asParadigmCategory_forms,
        GfkwdetailsData_details_lemma_subForms__base,
        GfkwdetailsData_details_message;
import 'package:frysish/src/graphql/__generated__/fkwDetailQuery.req.gql.dart'
    show GfkwdetailsReq;
import 'package:frysish/src/graphql/__generated__/fkwDetailQuery.var.gql.dart'
    show GfkwdetailsVars;
import 'package:frysish/src/graphql/__generated__/fkwQuery.data.gql.dart'
    show
        GfkwlemmasData_lemmasearch_lemmas_subForms,
        GdetaillinkData,
        GfkwlemmasData,
        GfkwlemmasData_lemmasearch,
        GfkwlemmasData_lemmasearch_lemmas,
        GfkwlemmasData_lemmasearch_lemmas_link,
        GfkwlemmasData_lemmasearch_lemmas_subForms__asParadigm,
        GfkwlemmasData_lemmasearch_lemmas_subForms__asParadigmCategory,
        GfkwlemmasData_lemmasearch_lemmas_subForms__asParadigmCategory_forms,
        GfkwlemmasData_lemmasearch_lemmas_subForms__base,
        GfkwlemmasData_lemmasearch_lemmas_translations,
        GfkwlemmasData_lemmasearch_message;
import 'package:frysish/src/graphql/__generated__/fkwQuery.req.gql.dart'
    show GdetaillinkReq, GfkwlemmasReq;
import 'package:frysish/src/graphql/__generated__/fkwQuery.var.gql.dart'
    show GdetaillinkVars, GfkwlemmasVars;
import 'package:frysish/src/graphql/__generated__/lemmaQuery.data.gql.dart'
    show
        GlemmasData_lemmasearch_lemmas_subForms,
        GlemmasData,
        GlemmasData_lemmasearch,
        GlemmasData_lemmasearch_lemmas,
        GlemmasData_lemmasearch_lemmas_link,
        GlemmasData_lemmasearch_lemmas_subForms__asDutchism,
        GlemmasData_lemmasearch_lemmas_subForms__asParadigm,
        GlemmasData_lemmasearch_lemmas_subForms__asParadigmCategory,
        GlemmasData_lemmasearch_lemmas_subForms__asParadigmCategory_forms,
        GlemmasData_lemmasearch_lemmas_subForms__asSynonym,
        GlemmasData_lemmasearch_lemmas_subForms__asVariant,
        GlemmasData_lemmasearch_lemmas_subForms__base,
        GlemmasData_lemmasearch_lemmas_translations,
        GlemmasData_lemmasearch_message;
import 'package:frysish/src/graphql/__generated__/lemmaQuery.req.gql.dart'
    show GlemmasReq;
import 'package:frysish/src/graphql/__generated__/lemmaQuery.var.gql.dart'
    show GlemmasVars;
import 'package:frysish/src/graphql/__generated__/rhymeQuery.data.gql.dart'
    show
        GrhymeData,
        GrhymeData_rhyme,
        GrhymeData_rhyme_message,
        GrhymeData_rhyme_rhymeGroups,
        GrhymeData_rhyme_rhymeGroups_rhyming;
import 'package:frysish/src/graphql/__generated__/rhymeQuery.req.gql.dart'
    show GrhymeReq;
import 'package:frysish/src/graphql/__generated__/rhymeQuery.var.gql.dart'
    show GrhymeVars;
import 'package:frysish/src/graphql/__generated__/sources.data.gql.dart'
    show GsourcesData, GsourcesData_sources;
import 'package:frysish/src/graphql/__generated__/sources.req.gql.dart'
    show GsourcesReq;
import 'package:frysish/src/graphql/__generated__/sources.var.gql.dart'
    show GsourcesVars;
import 'package:frysish/src/graphql/__generated__/textQuery.data.gql.dart'
    show
        GtextsData_textsearch_texts,
        GtextsData_textsearch_texts__asCollocation_text_text,
        GtextsData_textsearch_texts__asCollocation_text_text__asI_textI,
        GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asQ_textQ,
        GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ,
        GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asI_textI,
        GtextsData_textsearch_texts__asCollocation_translations_text_text,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asQ_textQ,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asI_textI,
        GtextsData_textsearch_texts__asExample_text_text,
        GtextsData_textsearch_texts__asExample_text_text__asI_textI,
        GtextsData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ,
        GtextsData_textsearch_texts__asExample_text_text__asQ_textQ,
        GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI,
        GtextsData_textsearch_texts__asExample_translations_text_text,
        GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI,
        GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ,
        GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ,
        GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI,
        GtextsData_textsearch_texts__asProverb_text_text,
        GtextsData_textsearch_texts__asProverb_text_text__asI_textI,
        GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ,
        GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ,
        GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI,
        GtextsData_textsearch_texts__asProverb_translations_text_text,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI,
        GtxtData_text,
        GtxtData_text__asI_textI,
        GtxtData_text__asI_textI__asQ_textQ,
        GtxtData_text__asQ_textQ,
        GtxtData_text__asQ_textQ__asI_textI,
        GtextsData,
        GtextsData_textsearch,
        GtextsData_textsearch_message,
        GtextsData_textsearch_texts__asCollocation,
        GtextsData_textsearch_texts__asCollocation_link,
        GtextsData_textsearch_texts__asCollocation_text,
        GtextsData_textsearch_texts__asCollocation_text_text__asI,
        GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asQ,
        GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asQ_textQ__asT,
        GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asQ_textQ__base,
        GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asT,
        GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__base,
        GtextsData_textsearch_texts__asCollocation_text_text__asQ,
        GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asI,
        GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asI_textI__asT,
        GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asI_textI__base,
        GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asT,
        GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__base,
        GtextsData_textsearch_texts__asCollocation_text_text__asT,
        GtextsData_textsearch_texts__asCollocation_text_text__base,
        GtextsData_textsearch_texts__asCollocation_translations,
        GtextsData_textsearch_texts__asCollocation_translations_text,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asI,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asQ,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asQ_textQ__asT,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asQ_textQ__base,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asT,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__base,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asI,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asI_textI__asT,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asI_textI__base,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asT,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__base,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__asT,
        GtextsData_textsearch_texts__asCollocation_translations_text_text__base,
        GtextsData_textsearch_texts__asExample,
        GtextsData_textsearch_texts__asExample_link,
        GtextsData_textsearch_texts__asExample_text,
        GtextsData_textsearch_texts__asExample_text_text__asI,
        GtextsData_textsearch_texts__asExample_text_text__asI_textI__asQ,
        GtextsData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ__asT,
        GtextsData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ__base,
        GtextsData_textsearch_texts__asExample_text_text__asI_textI__asT,
        GtextsData_textsearch_texts__asExample_text_text__asI_textI__base,
        GtextsData_textsearch_texts__asExample_text_text__asQ,
        GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asI,
        GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI__asT,
        GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI__base,
        GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asT,
        GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__base,
        GtextsData_textsearch_texts__asExample_text_text__asT,
        GtextsData_textsearch_texts__asExample_text_text__base,
        GtextsData_textsearch_texts__asExample_translations,
        GtextsData_textsearch_texts__asExample_translations_text,
        GtextsData_textsearch_texts__asExample_translations_text_text__asI,
        GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ,
        GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ__asT,
        GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ__base,
        GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asT,
        GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__base,
        GtextsData_textsearch_texts__asExample_translations_text_text__asQ,
        GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI,
        GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI__asT,
        GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI__base,
        GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asT,
        GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__base,
        GtextsData_textsearch_texts__asExample_translations_text_text__asT,
        GtextsData_textsearch_texts__asExample_translations_text_text__base,
        GtextsData_textsearch_texts__asProverb,
        GtextsData_textsearch_texts__asProverb_link,
        GtextsData_textsearch_texts__asProverb_text,
        GtextsData_textsearch_texts__asProverb_text_text__asI,
        GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asQ,
        GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ__asT,
        GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ__base,
        GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asT,
        GtextsData_textsearch_texts__asProverb_text_text__asI_textI__base,
        GtextsData_textsearch_texts__asProverb_text_text__asQ,
        GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI,
        GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI__asT,
        GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI__base,
        GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asT,
        GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__base,
        GtextsData_textsearch_texts__asProverb_text_text__asT,
        GtextsData_textsearch_texts__asProverb_text_text__base,
        GtextsData_textsearch_texts__asProverb_translations,
        GtextsData_textsearch_texts__asProverb_translations_text,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asI,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__asT,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__base,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asT,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__base,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asQ,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__asT,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__base,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asT,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__base,
        GtextsData_textsearch_texts__asProverb_translations_text_text__asT,
        GtextsData_textsearch_texts__asProverb_translations_text_text__base,
        GtextsData_textsearch_texts__base,
        GtxtData,
        GtxtData_text__asI,
        GtxtData_text__asI_textI__asQ,
        GtxtData_text__asI_textI__asQ_textQ__asT,
        GtxtData_text__asI_textI__asQ_textQ__base,
        GtxtData_text__asI_textI__asT,
        GtxtData_text__asI_textI__base,
        GtxtData_text__asQ,
        GtxtData_text__asQ_textQ__asI,
        GtxtData_text__asQ_textQ__asI_textI__asT,
        GtxtData_text__asQ_textQ__asI_textI__base,
        GtxtData_text__asQ_textQ__asT,
        GtxtData_text__asQ_textQ__base,
        GtxtData_text__asT,
        GtxtData_text__base,
        GtxtlinkData;
import 'package:frysish/src/graphql/__generated__/textQuery.req.gql.dart'
    show GtextsReq, GtxtReq, GtxtlinkReq;
import 'package:frysish/src/graphql/__generated__/textQuery.var.gql.dart'
    show GtextsVars, GtxtVars, GtxtlinkVars;
import 'package:frysish/src/graphql/__generated__/translate.data.gql.dart'
    show GtranslateData, GtranslateData_translatetext;
import 'package:frysish/src/graphql/__generated__/translate.req.gql.dart'
    show GtranslateReq;
import 'package:frysish/src/graphql/__generated__/translate.var.gql.dart'
    show GtranslateVars;
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..add(GdetailsData_details_lemma_subForms.serializer)
  ..add(GdetailsData_details_translations_subForms.serializer)
  ..add(GfkwdetailsData_details_lemma_subForms.serializer)
  ..add(GfkwlemmasData_lemmasearch_lemmas_subForms.serializer)
  ..add(GlemmagraphData_subForms.serializer)
  ..add(GlemmasData_lemmasearch_lemmas_subForms.serializer)
  ..add(GnestedtextgraphData.serializer)
  ..add(GnestedtextgraphData__asExample_text_text.serializer)
  ..add(GnestedtextgraphData__asExample_text_text__asI_textI.serializer)
  ..add(GnestedtextgraphData__asExample_text_text__asI_textI__asQ_textQ
      .serializer)
  ..add(GnestedtextgraphData__asExample_text_text__asQ_textQ.serializer)
  ..add(GnestedtextgraphData__asExample_text_text__asQ_textQ__asI_textI
      .serializer)
  ..add(GnestedtextgraphData__asExample_translations_text_text.serializer)
  ..add(GnestedtextgraphData__asExample_translations_text_text__asI_textI
      .serializer)
  ..add(
      GnestedtextgraphData__asExample_translations_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GnestedtextgraphData__asExample_translations_text_text__asQ_textQ
      .serializer)
  ..add(
      GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtextData_text_text.serializer)
  ..add(GtextData_text_text__asI_textI.serializer)
  ..add(GtextData_text_text__asI_textI__asQ_textQ.serializer)
  ..add(GtextData_text_text__asQ_textQ.serializer)
  ..add(GtextData_text_text__asQ_textQ__asI_textI.serializer)
  ..add(GtextgraphData.serializer)
  ..add(GtextgraphData__asProverb_text_text.serializer)
  ..add(GtextgraphData__asProverb_text_text__asI_textI.serializer)
  ..add(GtextgraphData__asProverb_text_text__asI_textI__asQ_textQ.serializer)
  ..add(GtextgraphData__asProverb_text_text__asQ_textQ.serializer)
  ..add(GtextgraphData__asProverb_text_text__asQ_textQ__asI_textI.serializer)
  ..add(GtextgraphData__asProverb_translations_text_text.serializer)
  ..add(GtextgraphData__asProverb_translations_text_text__asI_textI.serializer)
  ..add(GtextgraphData__asProverb_translations_text_text__asI_textI__asQ_textQ
      .serializer)
  ..add(GtextgraphData__asProverb_translations_text_text__asQ_textQ.serializer)
  ..add(GtextgraphData__asProverb_translations_text_text__asQ_textQ__asI_textI
      .serializer)
  ..add(GtextsData_textsearch_texts.serializer)
  ..add(GtextsData_textsearch_texts__asCollocation_text_text.serializer)
  ..add(GtextsData_textsearch_texts__asCollocation_text_text__asI_textI
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtextsData_textsearch_texts__asCollocation_translations_text_text
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI
          .serializer)
  ..add(
      GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(
      GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ
          .serializer)
  ..add(
      GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtextsData_textsearch_texts__asExample_text_text.serializer)
  ..add(GtextsData_textsearch_texts__asExample_text_text__asI_textI.serializer)
  ..add(GtextsData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ
      .serializer)
  ..add(GtextsData_textsearch_texts__asExample_text_text__asQ_textQ.serializer)
  ..add(GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asExample_translations_text_text.serializer)
  ..add(GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtextsData_textsearch_texts__asProverb_text_text.serializer)
  ..add(GtextsData_textsearch_texts__asProverb_text_text__asI_textI.serializer)
  ..add(GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ
      .serializer)
  ..add(GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ.serializer)
  ..add(GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asProverb_translations_text_text.serializer)
  ..add(GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ
          .serializer)
  ..add(GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ
      .serializer)
  ..add(
      GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI
          .serializer)
  ..add(GtexttransData_text_text.serializer)
  ..add(GtexttransData_text_text__asI_textI.serializer)
  ..add(GtexttransData_text_text__asI_textI__asQ_textQ.serializer)
  ..add(GtexttransData_text_text__asQ_textQ.serializer)
  ..add(GtexttransData_text_text__asQ_textQ__asI_textI.serializer)
  ..add(GtxtData_text.serializer)
  ..add(GtxtData_text__asI_textI.serializer)
  ..add(GtxtData_text__asI_textI__asQ_textQ.serializer)
  ..add(GtxtData_text__asQ_textQ.serializer)
  ..add(GtxtData_text__asQ_textQ__asI_textI.serializer)
  ..add(GtxtDetailsData_text.serializer)
  ..add(GtxtDetailsData_text__asI_textI.serializer)
  ..add(GtxtDetailsData_text__asI_textI__asQ_textQ.serializer)
  ..add(GtxtDetailsData_text__asQ_textQ.serializer)
  ..add(GtxtDetailsData_text__asQ_textQ__asI_textI.serializer)
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GCategoryType,
  GGramType,
  GLangType,
  GMessageLevel,
  GNameType,
  GUsgType,
  GautocompleteData,
  GautocompleteData_lemmasearch,
  GautocompleteData_lemmasearch_lemmas,
  GautocompleteData_lemmasearch_message,
  GautocompleteReq,
  GautocompleteVars,
  GdetaillinkData,
  GdetaillinkReq,
  GdetaillinkVars,
  GdetailsData,
  GdetailsData_details,
  GdetailsData_details_lemma,
  GdetailsData_details_lemma_subForms__asDutchism,
  GdetailsData_details_lemma_subForms__asParadigm,
  GdetailsData_details_lemma_subForms__asParadigmCategory,
  GdetailsData_details_lemma_subForms__asParadigmCategory_forms,
  GdetailsData_details_lemma_subForms__asSynonym,
  GdetailsData_details_lemma_subForms__asVariant,
  GdetailsData_details_lemma_subForms__base,
  GdetailsData_details_texts,
  GdetailsData_details_translations,
  GdetailsData_details_translations_subForms__asDutchism,
  GdetailsData_details_translations_subForms__asParadigm,
  GdetailsData_details_translations_subForms__asParadigmCategory,
  GdetailsData_details_translations_subForms__asParadigmCategory_forms,
  GdetailsData_details_translations_subForms__asSynonym,
  GdetailsData_details_translations_subForms__asVariant,
  GdetailsData_details_translations_subForms__base,
  GdetailsReq,
  GdetailsVars,
  GfkwdetailsData,
  GfkwdetailsData_details,
  GfkwdetailsData_details_lemma,
  GfkwdetailsData_details_lemma_subForms__asParadigm,
  GfkwdetailsData_details_lemma_subForms__asParadigmCategory,
  GfkwdetailsData_details_lemma_subForms__asParadigmCategory_forms,
  GfkwdetailsData_details_lemma_subForms__base,
  GfkwdetailsData_details_message,
  GfkwdetailsReq,
  GfkwdetailsVars,
  GfkwlemmasData,
  GfkwlemmasData_lemmasearch,
  GfkwlemmasData_lemmasearch_lemmas,
  GfkwlemmasData_lemmasearch_lemmas_link,
  GfkwlemmasData_lemmasearch_lemmas_subForms__asParadigm,
  GfkwlemmasData_lemmasearch_lemmas_subForms__asParadigmCategory,
  GfkwlemmasData_lemmasearch_lemmas_subForms__asParadigmCategory_forms,
  GfkwlemmasData_lemmasearch_lemmas_subForms__base,
  GfkwlemmasData_lemmasearch_lemmas_translations,
  GfkwlemmasData_lemmasearch_message,
  GfkwlemmasReq,
  GfkwlemmasVars,
  GlemmagraphData,
  GlemmagraphData_subForms__asDutchism,
  GlemmagraphData_subForms__asParadigm,
  GlemmagraphData_subForms__asParadigmCategory,
  GlemmagraphData_subForms__asParadigmCategory_forms,
  GlemmagraphData_subForms__asSynonym,
  GlemmagraphData_subForms__asVariant,
  GlemmagraphData_subForms__base,
  GlemmagraphReq,
  GlemmagraphVars,
  GlemmalinkData,
  GlemmalinkReq,
  GlemmalinkVars,
  GlemmasData,
  GlemmasData_lemmasearch,
  GlemmasData_lemmasearch_lemmas,
  GlemmasData_lemmasearch_lemmas_link,
  GlemmasData_lemmasearch_lemmas_subForms__asDutchism,
  GlemmasData_lemmasearch_lemmas_subForms__asParadigm,
  GlemmasData_lemmasearch_lemmas_subForms__asParadigmCategory,
  GlemmasData_lemmasearch_lemmas_subForms__asParadigmCategory_forms,
  GlemmasData_lemmasearch_lemmas_subForms__asSynonym,
  GlemmasData_lemmasearch_lemmas_subForms__asVariant,
  GlemmasData_lemmasearch_lemmas_subForms__base,
  GlemmasData_lemmasearch_lemmas_translations,
  GlemmasData_lemmasearch_message,
  GlemmasReq,
  GlemmasVars,
  GnestedtextgraphData__asExample,
  GnestedtextgraphData__asExample_text,
  GnestedtextgraphData__asExample_text_text__asI,
  GnestedtextgraphData__asExample_text_text__asI_textI__asQ,
  GnestedtextgraphData__asExample_text_text__asI_textI__asQ_textQ__asT,
  GnestedtextgraphData__asExample_text_text__asI_textI__asQ_textQ__base,
  GnestedtextgraphData__asExample_text_text__asI_textI__asT,
  GnestedtextgraphData__asExample_text_text__asI_textI__base,
  GnestedtextgraphData__asExample_text_text__asL,
  GnestedtextgraphData__asExample_text_text__asL_link,
  GnestedtextgraphData__asExample_text_text__asQ,
  GnestedtextgraphData__asExample_text_text__asQ_textQ__asI,
  GnestedtextgraphData__asExample_text_text__asQ_textQ__asI_textI__asT,
  GnestedtextgraphData__asExample_text_text__asQ_textQ__asI_textI__base,
  GnestedtextgraphData__asExample_text_text__asQ_textQ__asT,
  GnestedtextgraphData__asExample_text_text__asQ_textQ__base,
  GnestedtextgraphData__asExample_text_text__asT,
  GnestedtextgraphData__asExample_text_text__base,
  GnestedtextgraphData__asExample_translations,
  GnestedtextgraphData__asExample_translations_text,
  GnestedtextgraphData__asExample_translations_text_text__asI,
  GnestedtextgraphData__asExample_translations_text_text__asI_textI__asQ,
  GnestedtextgraphData__asExample_translations_text_text__asI_textI__asQ_textQ__asT,
  GnestedtextgraphData__asExample_translations_text_text__asI_textI__asQ_textQ__base,
  GnestedtextgraphData__asExample_translations_text_text__asI_textI__asT,
  GnestedtextgraphData__asExample_translations_text_text__asI_textI__base,
  GnestedtextgraphData__asExample_translations_text_text__asL,
  GnestedtextgraphData__asExample_translations_text_text__asL_link,
  GnestedtextgraphData__asExample_translations_text_text__asQ,
  GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asI,
  GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asI_textI__asT,
  GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asI_textI__base,
  GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__asT,
  GnestedtextgraphData__asExample_translations_text_text__asQ_textQ__base,
  GnestedtextgraphData__asExample_translations_text_text__asT,
  GnestedtextgraphData__asExample_translations_text_text__base,
  GnestedtextgraphData__base,
  GnestedtextgraphReq,
  GnestedtextgraphVars,
  GparData,
  GparReq,
  GparVars,
  GrhymeData,
  GrhymeData_rhyme,
  GrhymeData_rhyme_message,
  GrhymeData_rhyme_rhymeGroups,
  GrhymeData_rhyme_rhymeGroups_rhyming,
  GrhymeReq,
  GrhymeVars,
  GsourcesData,
  GsourcesData_sources,
  GsourcesReq,
  GsourcesVars,
  GtextData,
  GtextData_text,
  GtextData_text_text__asI,
  GtextData_text_text__asI_textI__asQ,
  GtextData_text_text__asI_textI__asQ_textQ__asT,
  GtextData_text_text__asI_textI__asQ_textQ__base,
  GtextData_text_text__asI_textI__asT,
  GtextData_text_text__asI_textI__base,
  GtextData_text_text__asL,
  GtextData_text_text__asL_link,
  GtextData_text_text__asQ,
  GtextData_text_text__asQ_textQ__asI,
  GtextData_text_text__asQ_textQ__asI_textI__asT,
  GtextData_text_text__asQ_textQ__asI_textI__base,
  GtextData_text_text__asQ_textQ__asT,
  GtextData_text_text__asQ_textQ__base,
  GtextData_text_text__asT,
  GtextData_text_text__base,
  GtextReq,
  GtextVars,
  GtextgraphData__asProverb,
  GtextgraphData__asProverb_text,
  GtextgraphData__asProverb_text_text__asI,
  GtextgraphData__asProverb_text_text__asI_textI__asQ,
  GtextgraphData__asProverb_text_text__asI_textI__asQ_textQ__asT,
  GtextgraphData__asProverb_text_text__asI_textI__asQ_textQ__base,
  GtextgraphData__asProverb_text_text__asI_textI__asT,
  GtextgraphData__asProverb_text_text__asI_textI__base,
  GtextgraphData__asProverb_text_text__asL,
  GtextgraphData__asProverb_text_text__asL_link,
  GtextgraphData__asProverb_text_text__asQ,
  GtextgraphData__asProverb_text_text__asQ_textQ__asI,
  GtextgraphData__asProverb_text_text__asQ_textQ__asI_textI__asT,
  GtextgraphData__asProverb_text_text__asQ_textQ__asI_textI__base,
  GtextgraphData__asProverb_text_text__asQ_textQ__asT,
  GtextgraphData__asProverb_text_text__asQ_textQ__base,
  GtextgraphData__asProverb_text_text__asT,
  GtextgraphData__asProverb_text_text__base,
  GtextgraphData__asProverb_translations,
  GtextgraphData__asProverb_translations_text,
  GtextgraphData__asProverb_translations_text_text__asI,
  GtextgraphData__asProverb_translations_text_text__asI_textI__asQ,
  GtextgraphData__asProverb_translations_text_text__asI_textI__asQ_textQ__asT,
  GtextgraphData__asProverb_translations_text_text__asI_textI__asQ_textQ__base,
  GtextgraphData__asProverb_translations_text_text__asI_textI__asT,
  GtextgraphData__asProverb_translations_text_text__asI_textI__base,
  GtextgraphData__asProverb_translations_text_text__asL,
  GtextgraphData__asProverb_translations_text_text__asL_link,
  GtextgraphData__asProverb_translations_text_text__asQ,
  GtextgraphData__asProverb_translations_text_text__asQ_textQ__asI,
  GtextgraphData__asProverb_translations_text_text__asQ_textQ__asI_textI__asT,
  GtextgraphData__asProverb_translations_text_text__asQ_textQ__asI_textI__base,
  GtextgraphData__asProverb_translations_text_text__asQ_textQ__asT,
  GtextgraphData__asProverb_translations_text_text__asQ_textQ__base,
  GtextgraphData__asProverb_translations_text_text__asT,
  GtextgraphData__asProverb_translations_text_text__base,
  GtextgraphData__base,
  GtextgraphReq,
  GtextgraphVars,
  GtextsData,
  GtextsData_textsearch,
  GtextsData_textsearch_message,
  GtextsData_textsearch_texts__asCollocation,
  GtextsData_textsearch_texts__asCollocation_link,
  GtextsData_textsearch_texts__asCollocation_text,
  GtextsData_textsearch_texts__asCollocation_text_text__asI,
  GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asQ,
  GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asQ_textQ__asT,
  GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asQ_textQ__base,
  GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__asT,
  GtextsData_textsearch_texts__asCollocation_text_text__asI_textI__base,
  GtextsData_textsearch_texts__asCollocation_text_text__asQ,
  GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asI,
  GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asI_textI__asT,
  GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asI_textI__base,
  GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__asT,
  GtextsData_textsearch_texts__asCollocation_text_text__asQ_textQ__base,
  GtextsData_textsearch_texts__asCollocation_text_text__asT,
  GtextsData_textsearch_texts__asCollocation_text_text__base,
  GtextsData_textsearch_texts__asCollocation_translations,
  GtextsData_textsearch_texts__asCollocation_translations_text,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asI,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asQ,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asQ_textQ__asT,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asQ_textQ__base,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__asT,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asI_textI__base,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asI,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asI_textI__asT,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asI_textI__base,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__asT,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asQ_textQ__base,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__asT,
  GtextsData_textsearch_texts__asCollocation_translations_text_text__base,
  GtextsData_textsearch_texts__asExample,
  GtextsData_textsearch_texts__asExample_link,
  GtextsData_textsearch_texts__asExample_text,
  GtextsData_textsearch_texts__asExample_text_text__asI,
  GtextsData_textsearch_texts__asExample_text_text__asI_textI__asQ,
  GtextsData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ__asT,
  GtextsData_textsearch_texts__asExample_text_text__asI_textI__asQ_textQ__base,
  GtextsData_textsearch_texts__asExample_text_text__asI_textI__asT,
  GtextsData_textsearch_texts__asExample_text_text__asI_textI__base,
  GtextsData_textsearch_texts__asExample_text_text__asQ,
  GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asI,
  GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI__asT,
  GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asI_textI__base,
  GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__asT,
  GtextsData_textsearch_texts__asExample_text_text__asQ_textQ__base,
  GtextsData_textsearch_texts__asExample_text_text__asT,
  GtextsData_textsearch_texts__asExample_text_text__base,
  GtextsData_textsearch_texts__asExample_translations,
  GtextsData_textsearch_texts__asExample_translations_text,
  GtextsData_textsearch_texts__asExample_translations_text_text__asI,
  GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ,
  GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ__asT,
  GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asQ_textQ__base,
  GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__asT,
  GtextsData_textsearch_texts__asExample_translations_text_text__asI_textI__base,
  GtextsData_textsearch_texts__asExample_translations_text_text__asQ,
  GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI,
  GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI__asT,
  GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asI_textI__base,
  GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__asT,
  GtextsData_textsearch_texts__asExample_translations_text_text__asQ_textQ__base,
  GtextsData_textsearch_texts__asExample_translations_text_text__asT,
  GtextsData_textsearch_texts__asExample_translations_text_text__base,
  GtextsData_textsearch_texts__asProverb,
  GtextsData_textsearch_texts__asProverb_link,
  GtextsData_textsearch_texts__asProverb_text,
  GtextsData_textsearch_texts__asProverb_text_text__asI,
  GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asQ,
  GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ__asT,
  GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asQ_textQ__base,
  GtextsData_textsearch_texts__asProverb_text_text__asI_textI__asT,
  GtextsData_textsearch_texts__asProverb_text_text__asI_textI__base,
  GtextsData_textsearch_texts__asProverb_text_text__asQ,
  GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI,
  GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI__asT,
  GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asI_textI__base,
  GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__asT,
  GtextsData_textsearch_texts__asProverb_text_text__asQ_textQ__base,
  GtextsData_textsearch_texts__asProverb_text_text__asT,
  GtextsData_textsearch_texts__asProverb_text_text__base,
  GtextsData_textsearch_texts__asProverb_translations,
  GtextsData_textsearch_texts__asProverb_translations_text,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asI,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__asT,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asQ_textQ__base,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__asT,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asI_textI__base,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asQ,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__asT,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asI_textI__base,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__asT,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asQ_textQ__base,
  GtextsData_textsearch_texts__asProverb_translations_text_text__asT,
  GtextsData_textsearch_texts__asProverb_translations_text_text__base,
  GtextsData_textsearch_texts__base,
  GtextsReq,
  GtextsVars,
  GtexttransData,
  GtexttransData_text,
  GtexttransData_text_text__asI,
  GtexttransData_text_text__asI_textI__asQ,
  GtexttransData_text_text__asI_textI__asQ_textQ__asT,
  GtexttransData_text_text__asI_textI__asQ_textQ__base,
  GtexttransData_text_text__asI_textI__asT,
  GtexttransData_text_text__asI_textI__base,
  GtexttransData_text_text__asL,
  GtexttransData_text_text__asL_link,
  GtexttransData_text_text__asQ,
  GtexttransData_text_text__asQ_textQ__asI,
  GtexttransData_text_text__asQ_textQ__asI_textI__asT,
  GtexttransData_text_text__asQ_textQ__asI_textI__base,
  GtexttransData_text_text__asQ_textQ__asT,
  GtexttransData_text_text__asQ_textQ__base,
  GtexttransData_text_text__asT,
  GtexttransData_text_text__base,
  GtexttransReq,
  GtexttransVars,
  GtranslateData,
  GtranslateData_translatetext,
  GtranslateReq,
  GtranslateVars,
  GtxtData,
  GtxtData_text__asI,
  GtxtData_text__asI_textI__asQ,
  GtxtData_text__asI_textI__asQ_textQ__asT,
  GtxtData_text__asI_textI__asQ_textQ__base,
  GtxtData_text__asI_textI__asT,
  GtxtData_text__asI_textI__base,
  GtxtData_text__asQ,
  GtxtData_text__asQ_textQ__asI,
  GtxtData_text__asQ_textQ__asI_textI__asT,
  GtxtData_text__asQ_textQ__asI_textI__base,
  GtxtData_text__asQ_textQ__asT,
  GtxtData_text__asQ_textQ__base,
  GtxtData_text__asT,
  GtxtData_text__base,
  GtxtDetailsData,
  GtxtDetailsData_text__asI,
  GtxtDetailsData_text__asI_textI__asQ,
  GtxtDetailsData_text__asI_textI__asQ_textQ__asT,
  GtxtDetailsData_text__asI_textI__asQ_textQ__base,
  GtxtDetailsData_text__asI_textI__asT,
  GtxtDetailsData_text__asI_textI__base,
  GtxtDetailsData_text__asL,
  GtxtDetailsData_text__asL_link,
  GtxtDetailsData_text__asQ,
  GtxtDetailsData_text__asQ_textQ__asI,
  GtxtDetailsData_text__asQ_textQ__asI_textI__asT,
  GtxtDetailsData_text__asQ_textQ__asI_textI__base,
  GtxtDetailsData_text__asQ_textQ__asT,
  GtxtDetailsData_text__asQ_textQ__base,
  GtxtDetailsData_text__asT,
  GtxtDetailsData_text__base,
  GtxtDetailsReq,
  GtxtDetailsVars,
  GtxtReq,
  GtxtVars,
  GtxtlinkData,
  GtxtlinkReq,
  GtxtlinkVars,
])
final Serializers serializers = _serializersBuilder.build();
